### ISSUE TITLE
Set up an automated development environment

### ISSUE THREAD

**Issue by Jameskmonger** [Jameskmonger/courtroom#12]
Set up a grunt development environment which watches for changes, builds the projects to test-build and then runs the tests. This will help reduce the reliance on Atom for our building.

**Comment by SiAdcock** [comment]
Can I suggest using [Gulp](http://gulpjs.com/) instead of Grunt? It is capable of everything that Grunt can do, but it supports a coding style which feels more idiomatic to JavaScript. 

Whereas Grunt forces you to write a monolithic and opinionated config file, Gulp allows you to write small, composable tasks as pure code. I find that this offers a more natural and flexible interface. It's worth giving it a quick spike if you haven't tried it already.

**Comment by Jameskmonger** [comment]
Sure, I'll look into Gulp! I've changed the issue name to reflect this
